<?xml version="1.0" encoding="utf-8"?><Database Name="SQL_QUANYTHUVIEN" Class="SQL_QUANLYTHUVIENDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=HP;Initial Catalog=SQL_QUANYTHUVIEN;Integrated Security=True" SettingsObjectName="DAO.Properties.Settings" SettingsPropertyName="SQL_QUANYTHUVIENConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CHUYENMUC" Member="CHUYENMUCs">
    <Type Name="CHUYENMUC">
      <Column Name="MACHUYENMUC" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENCHUYENMUC" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="CHUYENMUC_PHANLOAISACH" Member="PHANLOAISACHes" ThisKey="MACHUYENMUC" OtherKey="MACHUYENMUC" Type="PHANLOAISACH" />
    </Type>
  </Table>
  <Table Name="dbo.DANGKY" Member="DANGKies">
    <Type Name="DANGKY">
      <Column Name="MADK" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="MADG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYDK" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="DAUSACH_DANGKY" Member="DAUSACH" ThisKey="MASACH" OtherKey="MASACH" Type="DAUSACH" IsForeignKey="true" />
      <Association Name="DOCGIA_DANGKY" Member="DOCGIA" ThisKey="MADG" OtherKey="MADG" Type="DOCGIA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DAUSACH" Member="DAUSACHes">
    <Type Name="DAUSACH">
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MALOAISACH" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="MAVITRI" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MATG" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="MANGONNGU" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="SOTRANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MANXB" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="SOTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DAUSACH_DANGKY" Member="DANGKies" ThisKey="MASACH" OtherKey="MASACH" Type="DANGKY" />
      <Association Name="DAUSACH_MUONSACH" Member="MUONSACHes" ThisKey="MASACH" OtherKey="MASACH" Type="MUONSACH" />
      <Association Name="DAUSACH_QUATRINHMUON" Member="QUATRINHMUONs" ThisKey="MASACH" OtherKey="MASACH" Type="QUATRINHMUON" />
      <Association Name="NGONNGU_DAUSACH" Member="NGONNGU" ThisKey="MANGONNGU" OtherKey="MANGONNGU" Type="NGONNGU" IsForeignKey="true" />
      <Association Name="NXB_DAUSACH" Member="NXB" ThisKey="MANXB" OtherKey="MANXB" Type="NXB" IsForeignKey="true" />
      <Association Name="PHANLOAISACH_DAUSACH" Member="PHANLOAISACH" ThisKey="MALOAISACH" OtherKey="MALOAI" Type="PHANLOAISACH" IsForeignKey="true" />
      <Association Name="TACGIA_DAUSACH" Member="TACGIA" ThisKey="MATG" OtherKey="MATG" Type="TACGIA" IsForeignKey="true" />
      <Association Name="VITRI_DAUSACH" Member="VITRI" ThisKey="MAVITRI" OtherKey="MAVITRI" Type="VITRI" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DOCGIA" Member="DOCGIAs">
    <Type Name="DOCGIA">
      <Column Name="MADG" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NOISINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MALOP" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="MALOAIDOCGIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="DOCGIA_DANGKY" Member="DANGKies" ThisKey="MADG" OtherKey="MADG" Type="DANGKY" />
      <Association Name="DOCGIA_MUONSACH" Member="MUONSACHes" ThisKey="MADG" OtherKey="MADG" Type="MUONSACH" />
      <Association Name="DOCGIA_QUATRINHMUON" Member="QUATRINHMUONs" ThisKey="MADG" OtherKey="MADG" Type="QUATRINHMUON" />
      <Association Name="LOAIDOCGIA_DOCGIA" Member="LOAIDOCGIA" ThisKey="MALOAIDOCGIA" OtherKey="MALOAIDOCGIA" Type="LOAIDOCGIA" IsForeignKey="true" />
      <Association Name="LOP_DOCGIA" Member="LOP" ThisKey="MALOP" OtherKey="MALOP" Type="LOP" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KHOA" Member="KHOAs">
    <Type Name="KHOA">
      <Column Name="MAKHOA" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKHOA" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="TRUONGKHOA" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="KHOA_LOP" Member="LOPs" ThisKey="MAKHOA" OtherKey="MAKHOA" Type="LOP" />
    </Type>
  </Table>
  <Table Name="dbo.LOAIDOCGIA" Member="LOAIDOCGIAs">
    <Type Name="LOAIDOCGIA">
      <Column Name="MALOAIDOCGIA" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENDOCGIA" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="LOAIDOCGIA_DOCGIA" Member="DOCGIAs" ThisKey="MALOAIDOCGIA" OtherKey="MALOAIDOCGIA" Type="DOCGIA" />
    </Type>
  </Table>
  <Table Name="dbo.LOP" Member="LOPs">
    <Type Name="LOP">
      <Column Name="MALOP" Type="System.String" DbType="VarChar(8) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MAKHOA" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="GVCN" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="LOP_DOCGIA" Member="DOCGIAs" ThisKey="MALOP" OtherKey="MALOP" Type="DOCGIA" />
      <Association Name="KHOA_LOP" Member="KHOA" ThisKey="MAKHOA" OtherKey="MAKHOA" Type="KHOA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MUONSACH" Member="MUONSACHes">
    <Type Name="MUONSACH">
      <Column Name="MAPHIEUMUON" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MADG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="NGAYMUON" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NGAYTRA" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Association Name="DOCGIA_MUONSACH" Member="DOCGIA" ThisKey="MADG" OtherKey="MADG" Type="DOCGIA" IsForeignKey="true" />
      <Association Name="DAUSACH_MUONSACH" Member="DAUSACH" ThisKey="MASACH" OtherKey="MASACH" Type="DAUSACH" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NGONNGU" Member="NGONNGUs">
    <Type Name="NGONNGU">
      <Column Name="MANGONNGU" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNGONNGU" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="NGONNGU_DAUSACH" Member="DAUSACHes" ThisKey="MANGONNGU" OtherKey="MANGONNGU" Type="DAUSACH" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="MANV" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNV" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="CHUCVU" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="PASS" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="NHANVIEN_USER_LOG" Member="USER_LOG" ThisKey="MANV" OtherKey="ID" Type="USER_LOG" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.NXB" Member="NXBs">
    <Type Name="NXB">
      <Column Name="MANXB" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENNXB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="FAX" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="WEBSITE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="NXB_DAUSACH" Member="DAUSACHes" ThisKey="MANXB" OtherKey="MANXB" Type="DAUSACH" />
    </Type>
  </Table>
  <Table Name="dbo.PHANLOAISACH" Member="PHANLOAISACHes">
    <Type Name="PHANLOAISACH">
      <Column Name="MALOAI" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MACHUYENMUC" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Association Name="PHANLOAISACH_DAUSACH" Member="DAUSACHes" ThisKey="MALOAI" OtherKey="MALOAISACH" Type="DAUSACH" />
      <Association Name="CHUYENMUC_PHANLOAISACH" Member="CHUYENMUC" ThisKey="MACHUYENMUC" OtherKey="MACHUYENMUC" Type="CHUYENMUC" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QUATRINHMUON" Member="QUATRINHMUONs">
    <Type Name="QUATRINHMUON">
      <Column Name="MAPHIEUMUON" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MADG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="NGAYMUON" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NGAYTRA" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="SONGAYTRE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LYDO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TIENPHAT" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="NGAYPHAT" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="DAUSACH_QUATRINHMUON" Member="DAUSACH" ThisKey="MASACH" OtherKey="MASACH" Type="DAUSACH" IsForeignKey="true" />
      <Association Name="DOCGIA_QUATRINHMUON" Member="DOCGIA" ThisKey="MADG" OtherKey="MADG" Type="DOCGIA" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QUIDINH" Member="QUIDINHs">
    <Type Name="QUIDINH">
      <Column Name="MAQUIDINH" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENQUIDINH" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MUCPHAT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOTIEN" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TACGIA" Member="TACGIAs">
    <Type Name="TACGIA">
      <Column Name="MATG" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENTG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="FAX" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="TACGIA_DAUSACH" Member="DAUSACHes" ThisKey="MATG" OtherKey="MATG" Type="DAUSACH" />
    </Type>
  </Table>
  <Table Name="dbo.USER_LOG" Member="USER_LOGs">
    <Type Name="USER_LOG">
      <Column Name="ID" Type="System.String" DbType="VarChar(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LOGIN_LOG" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="LOOUT_LOG" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="NHANVIEN_USER_LOG" Member="NHANVIEN" ThisKey="ID" OtherKey="MANV" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.VITRI" Member="VITRIs">
    <Type Name="VITRI">
      <Column Name="MAVITRI" Type="System.String" DbType="VarChar(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="KHO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="VITRI_DAUSACH" Member="DAUSACHes" ThisKey="MAVITRI" OtherKey="MAVITRI" Type="DAUSACH" />
    </Type>
  </Table>
  <Function Name="dbo.sp_CheckMaPhieuMuon" Method="sp_CheckMaPhieuMuon">
    <Parameter Name="maphm" Type="System.String" DbType="VarChar(6)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_XOATHELOAI" Method="SP_XOATHELOAI">
    <Parameter Name="MALOAI" Parameter="mALOAI" Type="System.String" DbType="VarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_DeleteDuLieuPhieuMuon" Method="sp_DeleteDuLieuPhieuMuon">
    <Parameter Name="mapm" Type="System.String" DbType="VarChar(6)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_DeleteDuLieuQuaTrinhMuon" Method="sp_DeleteDuLieuQuaTrinhMuon">
    <Parameter Name="mapm" Type="System.String" DbType="VarChar(6)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_DemoDangKi" Method="sp_DemoDangKi">
    <ElementType Name="sp_DemoDangKiResult">
      <Column Name="MADK" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="MADG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAYDK" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_InsertDuLieuDangKi" Method="sp_InsertDuLieuDangKi">
    <Parameter Name="madk" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="masach" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="madg" Type="System.Int32" DbType="Int" />
    <Parameter Name="ngaydk" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="ghichu" Type="System.String" DbType="NVarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_InsertDuLieuPhieuMuonSach" Method="sp_InsertDuLieuPhieuMuonSach">
    <Parameter Name="mapm" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="madg" Type="System.Int32" DbType="Int" />
    <Parameter Name="masach" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="ngaymuon" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="ngaytra" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="ghichu" Type="System.String" DbType="VarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_InsertduLieuQuaTrinhMuon" Method="sp_InsertduLieuQuaTrinhMuon">
    <Parameter Name="phieums" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="madg" Type="System.Int32" DbType="Int" />
    <Parameter Name="masach" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="ngaymuon" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="ngaytra" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="songaytre" Type="System.Int32" DbType="Int" />
    <Parameter Name="lydo" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="tienphat" Type="System.Decimal" DbType="Money" />
    <Parameter Name="ngayphat" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="ghichu" Type="System.String" DbType="NVarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_KiemTraSosachChuaTraTheoMaDG" Method="sp_KiemTraSosachChuaTraTheoMaDG">
    <Parameter Name="madocgia" Type="System.Int32" DbType="Int" />
    <Parameter Name="sosach" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_KiemTraSosachChuaTraTheoMaSach" Method="sp_KiemTraSosachChuaTraTheoMaSach">
    <Parameter Name="masach" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="sosach" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_KiemTraSosachChuaTraTheoTenDG" Method="sp_KiemTraSosachChuaTraTheoTenDG">
    <Parameter Name="tendg" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="sosach" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_KiemTraSosachChuaTraTheoTenSach" Method="sp_KiemTraSosachChuaTraTheoTenSach">
    <Parameter Name="tensach" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="sosach" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_LAYDULIEUCHUYENMUC" Method="SP_LAYDULIEUCHUYENMUC">
    <ElementType Name="SP_LAYDULIEUCHUYENMUCResult">
      <Column Name="MACHUYENMUC" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TENCHUYENMUC" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_LAYDULIEUDG" Method="SP_LAYDULIEUDG">
    <ElementType Name="SP_LAYDULIEUDGResult">
      <Column Name="MADG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TENDG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NOISINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MALOP" Type="System.String" DbType="VarChar(8)" CanBeNull="true" />
      <Column Name="MALOAIDOCGIA" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_LayDuLieuMuonSach" Method="sp_LayDuLieuMuonSach">
    <ElementType Name="sp_LayDuLieuMuonSachResult">
      <Column Name="MAPHIEUMUON" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MADG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENDG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NGAYMUON" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NGAYTRA" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_LAYDULIEUNGONNGU" Method="SP_LAYDULIEUNGONNGU">
    <ElementType Name="SP_LAYDULIEUNGONNGUResult">
      <Column Name="MANGONNGU" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TENNGONNGU" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_LAYDULIEUNXB" Method="SP_LAYDULIEUNXB">
    <ElementType Name="SP_LAYDULIEUNXBResult">
      <Column Name="MANXB" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="TENNXB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="FAX" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="WEBSITE" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_LayDuLieuQuaTrinhMuon" Method="sp_LayDuLieuQuaTrinhMuon">
    <ElementType Name="sp_LayDuLieuQuaTrinhMuonResult">
      <Column Name="MAPHIEUMUON" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MADG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENDG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NGAYMUON" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NGAYTRA" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="SONGAYTRE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TIENPHAT" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="NGAYPHAT" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="LYDO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_LAYDULIEUSACH" Method="SP_LAYDULIEUSACH">
    <ElementType Name="SP_LAYDULIEUSACHResult">
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MALOAISACH" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="MATG" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="MANGONNGU" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="SOTRANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MANXB" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="SOTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="MAVITRI" Type="System.String" DbType="VarChar(6)" CanBeNull="true" />
      <Column Name="KHO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KE" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_LAYDULIEUTG" Method="SP_LAYDULIEUTG">
    <ElementType Name="SP_LAYDULIEUTGResult">
      <Column Name="MATG" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TENTG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="FAX" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_LAYDULIEUTHELOAI" Method="SP_LAYDULIEUTHELOAI">
    <ElementType Name="SP_LAYDULIEUTHELOAIResult">
      <Column Name="MALOAI" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MACHUYENMUC" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SUACHUYENMUC" Method="SP_SUACHUYENMUC">
    <Parameter Name="MACHUYENMUC" Parameter="mACHUYENMUC" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="TENCHUYENMUC" Parameter="tENCHUYENMUC" Type="System.String" DbType="NVarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SUADG" Method="SP_SUADG">
    <Parameter Name="MADG" Parameter="mADG" Type="System.Int32" DbType="Int" />
    <Parameter Name="TENDG" Parameter="tENDG" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="GIOITINH" Parameter="gIOITINH" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="NGAYSINH" Parameter="nGAYSINH" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="NOISINH" Parameter="nOISINH" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DIACHI" Parameter="dIACHI" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DIENTHOAI" Parameter="dIENTHOAI" Type="System.String" DbType="VarChar(11)" />
    <Parameter Name="EMAIL" Parameter="eMAIL" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="MALOP" Parameter="mALOP" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="MALOAIDOCGIA" Parameter="mALOAIDOCGIA" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SUANXB" Method="SP_SUANXB">
    <Parameter Name="MANXB" Parameter="mANXB" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="TENNXB" Parameter="tENNXB" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="DIACHI" Parameter="dIACHI" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="DIENTHOAI" Parameter="dIENTHOAI" Type="System.String" DbType="VarChar(11)" />
    <Parameter Name="FAX" Parameter="fAX" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="EMAIL" Parameter="eMAIL" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="WEBSITE" Parameter="wEBSITE" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="GHICHU" Parameter="gHICHU" Type="System.String" DbType="NVarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SUASACH" Method="SP_SUASACH">
    <Parameter Name="MASACH" Parameter="mASACH" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="TENSACH" Parameter="tENSACH" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="LOAISACH" Parameter="lOAISACH" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="TACGIA" Parameter="tACGIA" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="NN" Parameter="nN" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="SOTRANG" Parameter="sOTRANG" Type="System.Int32" DbType="Int" />
    <Parameter Name="NXB" Parameter="nXB" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="SOTIEN" Parameter="sOTIEN" Type="System.Decimal" DbType="Money" />
    <Parameter Name="MAVITRI" Parameter="mAVITRI" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="KHO" Parameter="kHO" Type="System.Int32" DbType="Int" />
    <Parameter Name="NGAN" Parameter="nGAN" Type="System.Int32" DbType="Int" />
    <Parameter Name="KE" Parameter="kE" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SUATG" Method="SP_SUATG">
    <Parameter Name="MATG" Parameter="mATG" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="TENTG" Parameter="tENTG" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="DIACHI" Parameter="dIACHI" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="DIENTHOAI" Parameter="dIENTHOAI" Type="System.String" DbType="VarChar(11)" />
    <Parameter Name="FAX" Parameter="fAX" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="EMAIL" Parameter="eMAIL" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="GHICHU" Parameter="gHICHU" Type="System.String" DbType="VarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SUATHELOAI" Method="SP_SUATHELOAI">
    <Parameter Name="MALOAI" Parameter="mALOAI" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="TENLOAI" Parameter="tENLOAI" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="MACHUYENMUC" Parameter="mACHUYENMUC" Type="System.String" DbType="VarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_THEMCHUYENMUC" Method="SP_THEMCHUYENMUC">
    <Parameter Name="MACHUYENMUC" Parameter="mACHUYENMUC" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="TENCHUYENMUC" Parameter="tENCHUYENMUC" Type="System.String" DbType="NVarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_THEMDG" Method="SP_THEMDG">
    <Parameter Name="MADG" Parameter="mADG" Type="System.Int32" DbType="Int" />
    <Parameter Name="TENDG" Parameter="tENDG" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="GIOITINH" Parameter="gIOITINH" Type="System.String" DbType="VarChar(3)" />
    <Parameter Name="NGAYSINH" Parameter="nGAYSINH" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="NOISINH" Parameter="nOISINH" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DIACHI" Parameter="dIACHI" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DIENTHOAI" Parameter="dIENTHOAI" Type="System.String" DbType="VarChar(11)" />
    <Parameter Name="EMAIL" Parameter="eMAIL" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="MALOP" Parameter="mALOP" Type="System.String" DbType="VarChar(8)" />
    <Parameter Name="MALOAIDOCGIA" Parameter="mALOAIDOCGIA" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_THEMNXB" Method="SP_THEMNXB">
    <Parameter Name="MANXB" Parameter="mANXB" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="TENNXB" Parameter="tENNXB" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="DIACHI" Parameter="dIACHI" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="DIENTHOAI" Parameter="dIENTHOAI" Type="System.String" DbType="VarChar(11)" />
    <Parameter Name="FAX" Parameter="fAX" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="EMAIL" Parameter="eMAIL" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="WEBSITE" Parameter="wEBSITE" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="GHICHU" Parameter="gHICHU" Type="System.String" DbType="NVarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_THEMSACH" Method="SP_THEMSACH">
    <Parameter Name="MASACH" Parameter="mASACH" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="TENSACH" Parameter="tENSACH" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="LOAISACH" Parameter="lOAISACH" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="TACGIA" Parameter="tACGIA" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="NN" Parameter="nN" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="SOTRANG" Parameter="sOTRANG" Type="System.Int32" DbType="Int" />
    <Parameter Name="NXB" Parameter="nXB" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="SOTIEN" Parameter="sOTIEN" Type="System.Decimal" DbType="Money" />
    <Parameter Name="MAVITRI" Parameter="mAVITRI" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="KHO" Parameter="kHO" Type="System.Int32" DbType="Int" />
    <Parameter Name="NGAN" Parameter="nGAN" Type="System.Int32" DbType="Int" />
    <Parameter Name="KE" Parameter="kE" Type="System.Int32" DbType="Int" />
    <Parameter Name="SL" Parameter="sL" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_THEMTG" Method="SP_THEMTG">
    <Parameter Name="MATG" Parameter="mATG" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="TENTG" Parameter="tENTG" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="DIACHI" Parameter="dIACHI" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="DIENTHOAI" Parameter="dIENTHOAI" Type="System.String" DbType="VarChar(11)" />
    <Parameter Name="FAX" Parameter="fAX" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="EMAIL" Parameter="eMAIL" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="GHICHU" Parameter="gHICHU" Type="System.String" DbType="VarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_THEMTHELOAI" Method="SP_THEMTHELOAI">
    <Parameter Name="MALOAI" Parameter="mALOAI" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="TENLOAI" Parameter="tENLOAI" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="MACHUYENMUC" Parameter="mACHUYENMUC" Type="System.String" DbType="VarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ThongKe_BaoCaoBanDocQuaHan" Method="sp_ThongKe_BaoCaoBanDocQuaHan">
    <Parameter Name="loai" Type="System.Int32" DbType="Int" />
    <Parameter Name="tungay" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="denngay" Type="System.DateTime" DbType="SmallDateTime" />
    <ElementType Name="sp_ThongKe_BaoCaoBanDocQuaHanResult">
      <Column Name="MADG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TENDG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NGAYMUON" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NGAYTRA" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="SONGAYTRE" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ThongKe_BaoCaoSach" Method="sp_ThongKe_BaoCaoSach">
    <ElementType Name="sp_ThongKe_BaoCaoSachResult">
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TENTG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TENNXB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOTRANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENNGONNGU" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SOTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="KHO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SLDANGMUON" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimDauSachTheoMaTaiLieu" Method="sp_TimDauSachTheoMaTaiLieu">
    <Parameter Name="masach" Type="System.String" DbType="VarChar(5)" />
    <ElementType Name="sp_TimDauSachTheoMaTaiLieuResult">
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TENTG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TENNXB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOTRANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENNGONNGU" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SOTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="KHO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SLDANGMUON" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimDauSachTheoTacGia" Method="sp_TimDauSachTheoTacGia">
    <Parameter Name="tentg" Type="System.String" DbType="NVarChar(30)" />
    <ElementType Name="sp_TimDauSachTheoTacGiaResult">
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TENTG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TENNXB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOTRANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENNGONNGU" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SOTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="KHO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SLDANGMUON" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimDauSachTheoTenNXB" Method="sp_TimDauSachTheoTenNXB">
    <Parameter Name="tennxb" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_TimDauSachTheoTenNXBResult">
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TENTG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TENNXB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOTRANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENNGONNGU" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SOTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="KHO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SLDANGMUON" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimDauSachTheoTenTaiLieu" Method="sp_TimDauSachTheoTenTaiLieu">
    <Parameter Name="tensach" Type="System.String" DbType="NVarChar(30)" />
    <ElementType Name="sp_TimDauSachTheoTenTaiLieuResult">
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TENTG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TENNXB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOTRANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENNGONNGU" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SOTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="KHO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SLDANGMUON" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimDauSachTheoTenTheLoai" Method="sp_TimDauSachTheoTenTheLoai">
    <Parameter Name="tentheloai" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_TimDauSachTheoTenTheLoaiResult">
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TENTG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="TENNXB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TENLOAI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SOTRANG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENNGONNGU" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="SOTIEN" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="KHO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SLDANGMUON" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimDocGiaTheoHoTen" Method="sp_TimDocGiaTheoHoTen">
    <Parameter Name="hoten" Type="System.String" DbType="NVarChar(30)" />
    <ElementType Name="sp_TimDocGiaTheoHoTenResult">
      <Column Name="MADG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TENDOCGIA" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TENDG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NOISINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TENLOP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TENKHOA" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimDocGiaTheoKhoa" Method="sp_TimDocGiaTheoKhoa">
    <Parameter Name="tenkhoa" Type="System.String" DbType="NVarChar(20)" />
    <ElementType Name="sp_TimDocGiaTheoKhoaResult">
      <Column Name="MADG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TENDOCGIA" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TENDG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NOISINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TENLOP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TENKHOA" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimDocGiaTheoLop" Method="sp_TimDocGiaTheoLop">
    <Parameter Name="tenlop" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_TimDocGiaTheoLopResult">
      <Column Name="MADG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TENDOCGIA" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TENDG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NOISINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TENLOP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TENKHOA" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimDocGiaTheoMaGV" Method="sp_TimDocGiaTheoMaGV">
    <Parameter Name="magv" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_TimDocGiaTheoMaGVResult">
      <Column Name="MADG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TENDOCGIA" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TENDG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NOISINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TENLOP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TENKHOA" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimDocGiaTheoMSSV" Method="sp_TimDocGiaTheoMSSV">
    <Parameter Name="madg" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_TimDocGiaTheoMSSVResult">
      <Column Name="MADG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TENDOCGIA" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TENDG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NGAYSINH" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NOISINH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIENTHOAI" Type="System.String" DbType="VarChar(11)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="TENLOP" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TENKHOA" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimKiemPhieuMuonTheoMDG" Method="sp_TimKiemPhieuMuonTheoMDG">
    <Parameter Name="madocgia" Type="System.Int32" DbType="Int" />
    <Parameter Name="tungay" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="denngay" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="kt" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_TimKiemPhieuMuonTheoMDGResult">
      <Column Name="MAPHIEUMUON" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MADG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENDG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NGAYMUON" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NGAYTRA" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimKiemPhieuMuonTheoMPM" Method="sp_TimKiemPhieuMuonTheoMPM">
    <Parameter Name="mapm" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="tungay" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="denngay" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="kt" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_TimKiemPhieuMuonTheoMPMResult">
      <Column Name="MAPHIEUMUON" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MADG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENDG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NGAYMUON" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NGAYTRA" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimKiemPhieuMuonTheoMS" Method="sp_TimKiemPhieuMuonTheoMS">
    <Parameter Name="masach" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="tungay" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="denngay" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="kt" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_TimKiemPhieuMuonTheoMSResult">
      <Column Name="MAPHIEUMUON" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MADG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENDG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NGAYMUON" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NGAYTRA" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimKiemPhieuMuonTheoTenDG" Method="sp_TimKiemPhieuMuonTheoTenDG">
    <Parameter Name="tendg" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="tungay" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="denngay" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="kt" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_TimKiemPhieuMuonTheoTenDGResult">
      <Column Name="MAPHIEUMUON" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MADG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENDG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NGAYMUON" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NGAYTRA" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimKiemPhieuMuonTheoTenTaiLieu" Method="sp_TimKiemPhieuMuonTheoTenTaiLieu">
    <Parameter Name="tensach" Type="System.String" DbType="NVarChar(30)" />
    <ElementType Name="sp_TimKiemPhieuMuonTheoTenTaiLieuResult">
      <Column Name="MAPHIEUMUON" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MADG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENDG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NGAYMUON" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NGAYTRA" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimKiemQuaTrinhMuontheoMaDG" Method="sp_TimKiemQuaTrinhMuontheoMaDG">
    <Parameter Name="madg" Type="System.Int32" DbType="Int" />
    <Parameter Name="tungay" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="denngay" Type="System.DateTime" DbType="SmallDateTime" />
    <ElementType Name="sp_TimKiemQuaTrinhMuontheoMaDGResult">
      <Column Name="MAPHIEUMUON" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MADG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENDG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NGAYMUON" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NGAYTRA" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="SONGAYTRE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TIENPHAT" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="NGAYPHAT" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="LYDO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimKiemQuaTrinhMuontheoMaPhieu" Method="sp_TimKiemQuaTrinhMuontheoMaPhieu">
    <Parameter Name="maphieu" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="tungay" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="denngay" Type="System.DateTime" DbType="SmallDateTime" />
    <ElementType Name="sp_TimKiemQuaTrinhMuontheoMaPhieuResult">
      <Column Name="MAPHIEUMUON" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MADG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENDG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NGAYMUON" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NGAYTRA" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="SONGAYTRE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TIENPHAT" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="NGAYPHAT" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="LYDO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimKiemQuaTrinhMuontheoMaSach" Method="sp_TimKiemQuaTrinhMuontheoMaSach">
    <Parameter Name="masach" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="tungay" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="denngay" Type="System.DateTime" DbType="SmallDateTime" />
    <ElementType Name="sp_TimKiemQuaTrinhMuontheoMaSachResult">
      <Column Name="MAPHIEUMUON" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MADG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENDG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NGAYMUON" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NGAYTRA" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="SONGAYTRE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TIENPHAT" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="NGAYPHAT" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="LYDO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TimKiemQuaTrinhMuontheoTenDG" Method="sp_TimKiemQuaTrinhMuontheoTenDG">
    <Parameter Name="hoten" Type="System.String" DbType="NVarChar(30)" />
    <Parameter Name="tungay" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="denngay" Type="System.DateTime" DbType="SmallDateTime" />
    <ElementType Name="sp_TimKiemQuaTrinhMuontheoTenDGResult">
      <Column Name="MAPHIEUMUON" Type="System.String" DbType="VarChar(6) NOT NULL" CanBeNull="false" />
      <Column Name="MADG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TENDG" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MASACH" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="TENSACH" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NGAYMUON" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NGAYTRA" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="SONGAYTRE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TIENPHAT" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="NGAYPHAT" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="LYDO" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="TRANGTHAI" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_TinhToanTienPhat" Method="sp_TinhToanTienPhat">
    <Parameter Name="masach" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="maqd" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="day" Type="System.Int32" DbType="Int" />
    <Parameter Name="tienphat" Type="System.Double" DbType="Float" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UpdateDuLieuDangKi" Method="sp_UpdateDuLieuDangKi">
    <Parameter Name="madk" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="masach" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="madg" Type="System.Int32" DbType="Int" />
    <Parameter Name="ngaydk" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="ghichu" Type="System.String" DbType="NVarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UpdateDuLieuPhieuMuon" Method="sp_UpdateDuLieuPhieuMuon">
    <Parameter Name="mapm" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="madg" Type="System.Int32" DbType="Int" />
    <Parameter Name="masach" Type="System.String" DbType="VarChar(5)" />
    <Parameter Name="ngaymuon" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="ngaytra" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="ghichu" Type="System.String" DbType="VarChar(200)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UpdateDuLieuQuaTrinhMuon" Method="sp_UpdateDuLieuQuaTrinhMuon">
    <Parameter Name="mapm" Type="System.String" DbType="VarChar(6)" />
    <Parameter Name="lydo" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="ngaytra" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="songaytre" Type="System.Int32" DbType="Int" />
    <Parameter Name="tienphat" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_XOACHUYENMUC" Method="SP_XOACHUYENMUC">
    <Parameter Name="MACHUYENMUC" Parameter="mACHUYENMUC" Type="System.String" DbType="VarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_XOADG" Method="SP_XOADG">
    <Parameter Name="MADG" Parameter="mADG" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_XOANXB" Method="SP_XOANXB">
    <Parameter Name="MANXB" Parameter="mANXB" Type="System.String" DbType="VarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_XOASACH" Method="SP_XOASACH">
    <Parameter Name="MASACH" Parameter="mASACH" Type="System.String" DbType="VarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_XOATG" Method="SP_XOATG">
    <Parameter Name="MATG" Parameter="mATG" Type="System.String" DbType="VarChar(5)" />
    <Return Type="System.Int32" />
  </Function>
</Database>